package at.jku.ce.stockexchange.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2013-12-08T16:00:29.779+01:00
 * Generated source version: 2.3.7
 * 
 */
@WebServiceClient(name = "ExchangeServiceService", 
                  wsdlLocation = "http://140.78.73.67:8080/CEStockExchangeWS/services/exchangeservice?wsdl",
                  targetNamespace = "http://service.stockexchange.ce.jku.at/") 
public class ExchangeServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.stockexchange.ce.jku.at/", "ExchangeServiceService");
    public final static QName ExchangeServicePort = new QName("http://service.stockexchange.ce.jku.at/", "ExchangeServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://140.78.73.67:8080/CEStockExchangeWS/services/exchangeservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExchangeServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://140.78.73.67:8080/CEStockExchangeWS/services/exchangeservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExchangeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExchangeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ExchangeService
     */
    @WebEndpoint(name = "ExchangeServicePort")
    public ExchangeService getExchangeServicePort() {
        return super.getPort(ExchangeServicePort, ExchangeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeService
     */
    @WebEndpoint(name = "ExchangeServicePort")
    public ExchangeService getExchangeServicePort(WebServiceFeature... features) {
        return super.getPort(ExchangeServicePort, ExchangeService.class, features);
    }

}
