
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.stockexchange.service;

import java.net.ConnectException;
import java.rmi.RemoteException;
import java.util.logging.Logger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import at.jku.ce.juddi.UddiManager;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2013-12-09T10:22:13.436+01:00
 * Generated source version: 2.3.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ExchangeServiceService",
                      portName = "ExchangeServicePort",
                      targetNamespace = "http://service.stockexchange.ce.jku.at/",
//                      wsdlLocation = "http://140.78.73.67:8080/CEStockExchangeWS/services/exchangeservice?wsdl",
                      wsdlLocation = "http://localhost:8080/Group103StockExchange/services/exchangeservice?wsdl",
                      endpointInterface = "at.jku.ce.stockexchange.service.ExchangeService")
                      
public class ExchangeServiceImpl implements ExchangeService {

    private static final Logger LOG = Logger.getLogger(ExchangeServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#buyStock(java.lang.String  arg0 ,)int  arg1 )*
     */
    public at.jku.ce.stockexchange.service.Exchange buyStock(java.lang.String arg0,int arg1) { 
        LOG.info("Executing operation buyStock");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            at.jku.ce.stockexchange.service.Exchange _return = new at.jku.ce.stockexchange.service.Exchange();
            _return.setExchangeDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-12-09T10:22:13.479+01:00"));
            _return.setExecution(-793306726);
            _return.setOrder(1370601458);
            _return.setSale(true);
            at.jku.ce.stockexchange.service.Stock _returnStock = new at.jku.ce.stockexchange.service.Stock();
            _returnStock.setAvailability(570555653);
            _returnStock.setCurrency("Currency-2055774476");
            _returnStock.setIsin("Isin-808900241");
            _returnStock.setName("Name-1544187525");
            _returnStock.setPrice(Double.valueOf(0.8190092299634669));
            _returnStock.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-12-09T10:22:13.480+01:00"));
            _return.setStock(_returnStock);
            at.jku.ce.stockexchange.service.StockExchange _returnStockExchange = new at.jku.ce.stockexchange.service.StockExchange();
            _returnStockExchange.setMic("Mic-1331684973");
            _returnStockExchange.setName("Name551435560");
            _return.setStockExchange(_returnStockExchange);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#getExchanges(*
     */
    public java.util.List<at.jku.ce.stockexchange.service.Exchange> getExchanges() { 
        LOG.info("Executing operation getExchanges");
        try {
            java.util.List<at.jku.ce.stockexchange.service.Exchange> _return = new java.util.ArrayList<at.jku.ce.stockexchange.service.Exchange>();
            at.jku.ce.stockexchange.service.Exchange _returnVal1 = new at.jku.ce.stockexchange.service.Exchange();
            _returnVal1.setExchangeDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-12-09T10:22:13.481+01:00"));
            _returnVal1.setExecution(-335954541);
            _returnVal1.setOrder(339467115);
            _returnVal1.setSale(false);
            at.jku.ce.stockexchange.service.Stock _returnVal1Stock = new at.jku.ce.stockexchange.service.Stock();
            _returnVal1Stock.setAvailability(2050354425);
            _returnVal1Stock.setCurrency("Currency-1109706493");
            _returnVal1Stock.setIsin("Isin-2018394409");
            _returnVal1Stock.setName("Name527746862");
            _returnVal1Stock.setPrice(Double.valueOf(0.06795022630849146));
            _returnVal1Stock.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-12-09T10:22:13.482+01:00"));
            _returnVal1.setStock(_returnVal1Stock);
            at.jku.ce.stockexchange.service.StockExchange _returnVal1StockExchange = new at.jku.ce.stockexchange.service.StockExchange();
            _returnVal1StockExchange.setMic("Mic-1307673209");
            _returnVal1StockExchange.setName("Name-957765323");
            _returnVal1.setStockExchange(_returnVal1StockExchange);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#sellStock(java.lang.String  arg0 ,)int  arg1 )*
     */
    public void sellStock(java.lang.String arg0,int arg1) { 
        LOG.info("Executing operation sellStock");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#getStock(java.lang.String  arg0 )*
     */
    public at.jku.ce.stockexchange.service.Stock getStock(java.lang.String arg0) { 
        LOG.info("Executing operation getStock");
        System.out.println(arg0);
        try {
            at.jku.ce.stockexchange.service.Stock _return = new at.jku.ce.stockexchange.service.Stock();
            _return.setAvailability(-1559623490);
            _return.setCurrency("Currency968839514");
            _return.setIsin("Isin787362314");
            _return.setName("Name-1877762612");
            _return.setPrice(Double.valueOf(0.4630799930371601));
            _return.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-12-09T10:22:13.484+01:00"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#getTradedStocks(*
     */
    public java.util.List<at.jku.ce.stockexchange.service.Stock> getTradedStocks() { 
        LOG.info("Executing operation getTradedStocks");
        try {
            java.util.List<at.jku.ce.stockexchange.service.Stock> _return = new java.util.ArrayList<at.jku.ce.stockexchange.service.Stock>();
            at.jku.ce.stockexchange.service.Stock _returnVal1 = new at.jku.ce.stockexchange.service.Stock();
            _returnVal1.setAvailability(960547131);
            _returnVal1.setCurrency("Currency1391524812");
            _returnVal1.setIsin("Isin-1595635721");
            _returnVal1.setName("Name245625284");
            _returnVal1.setPrice(Double.valueOf(0.5374880929208302));
            _returnVal1.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-12-09T10:22:13.484+01:00"));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#reset(*
     */
    public void reset() { 
        LOG.info("Executing operation reset");
        try {
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
